<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <PublishProfile Condition="'$(PublishProfile)' == ''">Default</PublishProfile>
	  <Nullable>enable</Nullable>
    <AssemblyName>Hmy.Estao</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>ai-setting.ico</ApplicationIcon>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<Version>0.0.9-alpha</Version>
	<AssemblyVersion>0.0.9</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hmy.Estao.Core\Hmy.Estao.Core.csproj" />
    <ProjectReference Include="..\Zarpa.Controls.Net10\Zarpa.Controls.Net10.csproj" />
    <PackageReference Include="Svg" Version="3.4.8" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\ProviderIcons\*.svg" LogicalName="Hmy.Estao.ProviderIcons.%(Filename)%(Extension)" />
    <EmbeddedResource Include="Assets\usage-history.sample.json" LogicalName="Hmy.Estao.UsageHistorySample.json" />
  </ItemGroup>

<Target Name="pubre">
  	<Exec Command="dotnet publish -c Release -p:SelfContained=false -p:PublishSingleFile=true -r win-x64" />
  	<ItemGroup>
  		<PublishFiles Include="bin\Release\$(TargetFramework)\win-x64\publish\*" />
  	</ItemGroup>
  	<Copy SourceFiles="@(PublishFiles)" DestinationFolder="C:\_SHOFIANOVA" />
  </Target>
</Project>
